### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined /make-runnable/index.js:55:42

### ISSUE THREAD

**Issue by kevzettler** [super-cache-money/make-runnable#1]
test.js

```javascript
require('make-runnable');

module.exports = {
    addTogether: function(x,y){
        return x + y
    }, doSomethingWithObject: function(object){
        object.newKey = "easy AF";
        return object;
    }, simpleValue: 'also works'
};
```

```
Kevins-MBP:org-stream kevzettler$ node ./test.js addtogether 1 2
/Users/kevzettler/Dropbox (Personal)/code/org-stream/node_modules/make-runnable/index.js:55
      var egPropertyHasSpace = egProperty.indexOf(' ') > 0; //if example property
                                         ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.<anonymous> (/Users/kevzettler/Dropbox (Personal)/code/org-stream/node_modules/make-runnable/index.js:55:42)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kevzettler/Dropbox (Personal)/code/org-stream/test.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

versions
```
Kevins-MBP:org-stream kevzettler$ node -v && npm ls make-runnable
v4.2.6
/Users/kevzettler/Dropbox (Personal)/code/org-stream
└── make-runnable@1.0.3
```

**Comment by callym** [comment]
I had the same issue, fixed it by moving the `require('make-runnable');` line to the bottom of my file.

**Comment by super-cache-money** [comment]
This is now stipulated in the readme. Thank you!
